apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: "argocd-operator"
  namespace: "argocd"
  annotations: 
    olm.operatorGroup: argocd
spec:
  channel: "alpha" 
  installPlanApproval: "Automatic"
  source: "community-operators" 
  sourceNamespace: "openshift-marketplace"
  name: "argocd-operator"
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: "prometheus"
  namespace: "argocd"
  annotations: 
    olm.operatorGroup: argocd
spec:
  channel: "beta" 
  installPlanApproval: "Automatic"
  source: "community-operators" 
  sourceNamespace: "openshift-marketplace"
  name: "prometheus"

